twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/Email_Images': img

when@test:
    twig:
        strict_variables: true
